#include <torch/extension.h>

void vector_step_cuda(
    torch::Tensor actions,
    torch::Tensor enabled,
    torch::Tensor positions,
    torch::Tensor velocities,
    torch::Tensor frame_start_positions,
    torch::Tensor angles,
    torch::Tensor angular_velocities,
    torch::Tensor levels,
    torch::Tensor physics_radii,
    torch::Tensor masses,
    torch::Tensor inverse_masses,
    torch::Tensor inverse_inertias,
    torch::Tensor fruit_ids,
    torch::Tensor age_frames,
    torch::Tensor active,
    torch::Tensor fruit_queue,
    torch::Tensor score,
    torch::Tensor last_score,
    torch::Tensor step_count,
    torch::Tensor physics_frame,
    torch::Tensor fail_frames,
    torch::Tensor next_fruit_id,
    torch::Tensor rng_state,
    torch::Tensor terminated,
    torch::Tensor needs_reset,
    torch::Tensor last_drop_level,
    torch::Tensor last_drop_x,
    torch::Tensor last_drop_id,
    torch::Tensor last_queue_before,
    torch::Tensor last_queue_after,
    torch::Tensor event_count,
    torch::Tensor event_source_levels,
    torch::Tensor event_new_levels,
    torch::Tensor event_positions,
    torch::Tensor event_score_deltas,
    torch::Tensor event_source_ids,
    torch::Tensor event_new_fruit_ids,
    torch::Tensor display_radii,
    torch::Tensor dropped_radii,
    torch::Tensor merged_radii,
    torch::Tensor mass_table,
    torch::Tensor merge_scores,
    torch::Tensor frames_simulated,
    torch::Tensor fast_forwarded_frames,
    torch::Tensor collision_substeps,
    torch::Tensor stable_result,
    torch::Tensor done_result,
    torch::Tensor truncated_result,
    torch::Tensor trace_rows,
    torch::Tensor trace_positions,
    torch::Tensor trace_velocities,
    torch::Tensor trace_angles,
    torch::Tensor trace_angular_velocities,
    torch::Tensor trace_levels,
    torch::Tensor trace_physics_radii,
    torch::Tensor trace_fruit_ids,
    torch::Tensor trace_active,
    torch::Tensor trace_scores,
    torch::Tensor trace_merge_counts,
    torch::Tensor trace_frame_numbers,
    torch::Tensor trace_record_counts,
    int64_t trace_count,
    int64_t trace_capacity,
    int64_t trace_stride,
    int64_t board_width,
    int64_t board_height,
    int64_t spawn_y,
    int64_t wall_width,
    int64_t action_count,
    int64_t max_fruits,
    int64_t queue_length,
    int64_t physics_fps,
    int64_t max_physics_frames,
    int64_t stable_frames,
    int64_t solver_iterations,
    bool drop_fast_forward,
    bool adaptive_collision_substeps,
    int64_t max_collision_substeps,
    int64_t kinematic_rest_frames,
    double kinematic_rest_speed_epsilon,
    double gravity_y,
    double damping,
    double fruit_elasticity,
    double restitution_velocity_threshold,
    double fruit_friction,
    double wall_friction,
    double stable_velocity_epsilon,
    double stable_angular_velocity_epsilon,
    int64_t danger_frame_limit,
    double contact_slop,
    double position_correction,
    double merge_tolerance,
    double collision_substep_motion_fraction,
    double collision_substep_penetration_threshold,
    int64_t threads_per_block);

#define CHECK_CUDA(x) TORCH_CHECK(x.is_cuda(), #x " must be a CUDA tensor")
#define CHECK_CONTIGUOUS(x) TORCH_CHECK(x.is_contiguous(), #x " must be contiguous")

void vector_step(
    torch::Tensor actions,
    torch::Tensor enabled,
    torch::Tensor positions,
    torch::Tensor velocities,
    torch::Tensor frame_start_positions,
    torch::Tensor angles,
    torch::Tensor angular_velocities,
    torch::Tensor levels,
    torch::Tensor physics_radii,
    torch::Tensor masses,
    torch::Tensor inverse_masses,
    torch::Tensor inverse_inertias,
    torch::Tensor fruit_ids,
    torch::Tensor age_frames,
    torch::Tensor active,
    torch::Tensor fruit_queue,
    torch::Tensor score,
    torch::Tensor last_score,
    torch::Tensor step_count,
    torch::Tensor physics_frame,
    torch::Tensor fail_frames,
    torch::Tensor next_fruit_id,
    torch::Tensor rng_state,
    torch::Tensor terminated,
    torch::Tensor needs_reset,
    torch::Tensor last_drop_level,
    torch::Tensor last_drop_x,
    torch::Tensor last_drop_id,
    torch::Tensor last_queue_before,
    torch::Tensor last_queue_after,
    torch::Tensor event_count,
    torch::Tensor event_source_levels,
    torch::Tensor event_new_levels,
    torch::Tensor event_positions,
    torch::Tensor event_score_deltas,
    torch::Tensor event_source_ids,
    torch::Tensor event_new_fruit_ids,
    torch::Tensor display_radii,
    torch::Tensor dropped_radii,
    torch::Tensor merged_radii,
    torch::Tensor mass_table,
    torch::Tensor merge_scores,
    torch::Tensor frames_simulated,
    torch::Tensor fast_forwarded_frames,
    torch::Tensor collision_substeps,
    torch::Tensor stable_result,
    torch::Tensor done_result,
    torch::Tensor truncated_result,
    torch::Tensor trace_rows,
    torch::Tensor trace_positions,
    torch::Tensor trace_velocities,
    torch::Tensor trace_angles,
    torch::Tensor trace_angular_velocities,
    torch::Tensor trace_levels,
    torch::Tensor trace_physics_radii,
    torch::Tensor trace_fruit_ids,
    torch::Tensor trace_active,
    torch::Tensor trace_scores,
    torch::Tensor trace_merge_counts,
    torch::Tensor trace_frame_numbers,
    torch::Tensor trace_record_counts,
    int64_t trace_count,
    int64_t trace_capacity,
    int64_t trace_stride,
    int64_t board_width,
    int64_t board_height,
    int64_t spawn_y,
    int64_t wall_width,
    int64_t action_count,
    int64_t max_fruits,
    int64_t queue_length,
    int64_t physics_fps,
    int64_t max_physics_frames,
    int64_t stable_frames,
    int64_t solver_iterations,
    bool drop_fast_forward,
    bool adaptive_collision_substeps,
    int64_t max_collision_substeps,
    int64_t kinematic_rest_frames,
    double kinematic_rest_speed_epsilon,
    double gravity_y,
    double damping,
    double fruit_elasticity,
    double restitution_velocity_threshold,
    double fruit_friction,
    double wall_friction,
    double stable_velocity_epsilon,
    double stable_angular_velocity_epsilon,
    int64_t danger_frame_limit,
    double contact_slop,
    double position_correction,
    double merge_tolerance,
    double collision_substep_motion_fraction,
    double collision_substep_penetration_threshold,
    int64_t threads_per_block) {
  CHECK_CUDA(actions);
  CHECK_CONTIGUOUS(actions);
  CHECK_CUDA(enabled);
  CHECK_CONTIGUOUS(enabled);
  CHECK_CONTIGUOUS(positions);
  CHECK_CONTIGUOUS(frame_start_positions);
  TORCH_CHECK(actions.scalar_type() == torch::kInt64, "actions must be int64");
  TORCH_CHECK(enabled.scalar_type() == torch::kBool, "enabled must be bool");
  TORCH_CHECK(enabled.numel() == actions.numel(),
              "enabled must have one entry per environment");
  TORCH_CHECK(positions.scalar_type() == torch::kFloat32, "state floats must be float32");
  TORCH_CHECK(max_fruits <= 256, "compiled CUDA backend supports max_fruits <= 256");
  TORCH_CHECK(trace_stride > 0, "trace_stride must be positive");
  TORCH_CHECK(trace_count >= 0, "trace_count must be non-negative");
  if (trace_count > 0) {
    CHECK_CONTIGUOUS(trace_rows);
    CHECK_CONTIGUOUS(trace_positions);
    TORCH_CHECK(trace_rows.numel() == actions.numel(),
                "trace_rows must have one entry per environment");
    TORCH_CHECK(trace_record_counts.numel() == trace_count,
                "trace_record_counts must have one entry per trace");
  }
  vector_step_cuda(
      actions, enabled, positions, velocities, frame_start_positions,
      angles, angular_velocities, levels,
      physics_radii, masses, inverse_masses, inverse_inertias, fruit_ids,
      age_frames, active, fruit_queue, score, last_score, step_count,
      physics_frame, fail_frames, next_fruit_id, rng_state, terminated,
      needs_reset, last_drop_level, last_drop_x, last_drop_id,
      last_queue_before, last_queue_after, event_count,
      event_source_levels, event_new_levels, event_positions,
      event_score_deltas, event_source_ids, event_new_fruit_ids,
      display_radii, dropped_radii, merged_radii, mass_table, merge_scores,
      frames_simulated, fast_forwarded_frames, collision_substeps,
      stable_result, done_result, truncated_result,
      trace_rows, trace_positions, trace_velocities, trace_angles,
      trace_angular_velocities, trace_levels, trace_physics_radii,
      trace_fruit_ids, trace_active, trace_scores, trace_merge_counts,
      trace_frame_numbers, trace_record_counts, trace_count, trace_capacity,
      trace_stride,
      board_width, board_height, spawn_y, wall_width, action_count,
      max_fruits, queue_length, physics_fps, max_physics_frames,
      stable_frames, solver_iterations, drop_fast_forward,
      adaptive_collision_substeps, max_collision_substeps,
      kinematic_rest_frames,
      kinematic_rest_speed_epsilon, gravity_y, damping,
      fruit_elasticity, restitution_velocity_threshold,
      fruit_friction, wall_friction,
      stable_velocity_epsilon, stable_angular_velocity_epsilon,
      danger_frame_limit, contact_slop, position_correction,
      merge_tolerance, collision_substep_motion_fraction,
      collision_substep_penetration_threshold, threads_per_block);
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("vector_step", &vector_step, "Batched fruit physics step (CUDA)");
}
